### ISSUE TITLE
libre2 first readings are incorrect for the first hours of a new meter

### ISSUE THREAD

**Issue by codertrite** [gui-dos/DiaBLE#10]
Hi

I'm reading my second libre2 sensor and my sensor value is off for the first couple of hours. there is a 20mg/l difference between diaBLE and librelink.
is this known and something to be ignored or am I using it wrong?

**Comment by gui-dos** [comment]
Unfortunately the glucose.space server hasn’t been updated to the newer LibreLinks libraries and the LibreOOPWeb algorithm was giving similar results as the temperature-based calibration algorithm reversed by the FreeAPS X team (still derived from the old 2.3 version, however).

I dropped them like xDrip4iOS5 did: we share the same algorithm as the Android xDrip+ but ours are true open-sourced projects… ;-)
