### ISSUE TITLE
downgrade version

### ISSUE THREAD

**Issue by ddtch** [gui-dos/DiaBLE#11]
Hello, do you plan to downgrade the version at least to iOS 13 to allow installations on older devices?
I saw you edited libreTools but isn't it a more efficient way to separate NFC reading and data transformation

**Comment by gui-dos** [comment]
I am a kind of permanent beta tester and after the yearly WWDCs I like to play with the new announced features restarting from a new Xcode template: you can find a tagged 13.0 release at https://github.com/birdfly/DiaBLE/releases/tag/iOS13 dated on June, obviously :-)

I didn’t started from LibreTools: DiaBox and iDroplet, too, simply started from the details unveiled in https://github.com/gui-dos/DiaBLE/blob/master/Docs/techreport.pdf which I was the first one to discuss on Gittter about.
