### ISSUE TITLE
Can't read Libre2 US via NFC. 

### ISSUE THREAD

**Issue by ElevenRyu** [gui-dos/DiaBLE#13]
See the console in the screenshot below.
is it bug? or not supported Libre2 US?
![IMG_55B4CF5E97F8-1](https://github.com/gui-dos/DiaBLE/assets/126947253/a2383218-7504-4706-aa48-b208616f617b)

**Comment by gui-dos** [comment]
The layout of the 43 FRAM blocks of the “Gen2” sensors is the same as the previous generation, as well as the kind and the amount of data sent every minute via Bluetooth (three packets of 20 + 18 + 8 = 46 bytes encoding seven sparse trend values and the last three historical measurements): differently than the European firmware, however, the ephemeral keys are not fixed, but are generated for each new “secure” session.

You have first to request a “security challenge” by sending the single `0x20` byte via Bluetooth or the `A1 20` NFC custom subcommand and then follow the multi-stage protocols I am outlining in https://github.com/gui-dos/DiaBLE/blob/main/DiaBLE/Gen2.swift.

AFAIK, the Android DiaBox and Juggluco developers never succeeded in reverse-engineering the native C++ obfuscated `P1()` and `P2()` methods, either, and they must embed and redistribute the original `libdataprocessing.so` library, hence the DMCA takedown request.

**Comment by ElevenRyu** [comment]
@gui-dos Thx for the reply.
My goal is to get history, trend glucose data by NFC scan with Libre2 US. 
If I understand correctly, until p1 and p2 methods are implemented, I can't scan with Diable from this repository?

I checked the code you gave me and it references p1, p2.
https://github.com/gui-dos/DiaBLE/blob/5d2b3baf0fecb5a101bccfb479586a79578977a0/DiaBLE/Gen2.swift#L145

I hope for your reply.

**Comment by gui-dos** [comment]
Supersapiens has never obfuscated the package  `com.abbottdiabetescare.flashglucose.sensorabstractionservice.gen2security` (their “biosensor” is just a European rebrand of the US/CA/AU models) and neither has the latest LibreLink: I simply converted those definitions into Swift, since Juggluco uses numeric constants cryptically and I am just collecting the enums to better grasp the workflow logic.

Of curse I never tested them on iOS but I was told that those are the correct steps to take. The C++ “dataprocessing” library is statically embedded in the iOS single executable (the struct definitions are common between the iOS and Android implementations) but AFAIK reversing it is almost impossible on iOS (I am just exploring the decrypted executable with Hopper, not debugging it).

May I ask you whether other parts of my app work with the Libre 2 US, i.e. eavesdropping the incoming BLE data by running in parallel with the official app or scraping online the libreview.io  servers?

**Comment by ElevenRyu** [comment]
Thx. 
my overall understanding is still evolving, so please bear with me if some of my inquiries seem basic or if I'm missing some fundamental insights.

Question about BLE Communication with Libre 2: I've been considering whether BLE is the optimal method for interacting with the Libre 2 sensor. Could you offer any advice on this? Specifically, is BLE communication a recommended approach for collecting data from the Libre 2 sensor? I'm only trying it with NFC right now.

BLE Testing Procedure: I found bluetooth setup, but I'm unsure of the next steps to specifically test communication with the Libre 2 sensor. Could you provide any guidance or recommendations on how to proceed with BLE testing? Any specific tools or methods would be greatly appreciated.

Understanding the Diable Console Output:
I noticed that the Diable Console displays "43 Frame," but all CRC checks are marked as "Failed." Does this mean the frame data is still valid, or should I be concerned about these failures?
Could you help clarify the structure of the 43 Frame data? I'm trying to distinguish which parts represent trend data versus history data, but the distinction is not clear to me.

```
Sensor decrypted FRAM:
#00  D1 5C 49 36 5B 59 6F 26  .\I6[Yo&
#01  69 CC 8A E0 83 CA 55 44  i.....UD
#02  23 1C 33 AC A2 A1 50 80  #.3...P.
#03  5D 66 26 1C 43 26 FA 28  ]f&.C&.(
#04  28 01 3D E4 D8 2C 64 01  (.=..,d.
#05  A6 1C 70 1C 38 87 64 4A  ..p.8.dJ
#06  63 A6 7E 5D 0E 39 B5 DC  c.~].9..
#07  AF DA 70 61 88 7A 4D 04  ..pa.zM.
#08  EE 9A 8C 49 44 07 58 75  ...ID.Xu
#09  4E D2 82 8C 5F 7C 3F C8  N..._|?.
#0a  C3 71 3F BA 19 B8 0B E3  .q?.....
#0b  90 97 20 35 62 87 34 56  .. 5b.4V
#0c  EF 6D 9A D3 DB 9C 08 A8  .m......
#0d  D7 F2 86 D3 E0 E8 CE 89  ........
#0e  DC FA 80 76 78 51 D7 0A  ...vxQ..
#0f  DB 70 71 E8 EA 57 D1 CB  .pq..W..
#10  AA D2 70 91 20 FC 6B 2B  ..p. .k+
#11  7E B6 45 30 E6 61 B2 28  ~.E0.a.(
#12  C6 AE DD 11 2A 11 8E 46  ....*..F
#13  1D 04 52 4A BA 27 A5 AA  ..RJ.'..
#14  82 8A 77 4C A1 A8 49 BD  ..wL..I.
#15  03 E4 AB CC E2 41 05 7A  .....A.z
#16  7F D3 38 5C E4 4F 1D D6  ..8\.O..
#17  54 13 2E 01 FE 91 8F 93  T.......
#18  F7 EC AC 8D AA 5A 1C 1F  .....Z..
#19  1F 3C 3C D0 C7 59 FF 86  .<<..Y..
#1a  FC 95 93 43 52 68 0E FA  ...CRh..
#1b  63 DB 46 E2 F9 3E 00 00  c.F..>..
#1c  02 E9 44 32 1B BD 76 7D  ..D2..v}
#1d  8C 6F AD D5 4B 1E 71 2E  .o..K.q.
#1e  15 48 B5 1A 9C 17 4F 5B  .H....O[
#1f  DB A7 72 EA C3 6B 2B 6C  ..r..k+l
#20  FC 47 06 9A B8 17 18 AD  .G......
#21  D9 BD 12 B6 DA CF 53 AD  ......S.
#22  89 E6 F8 D9 8C 2A D9 90  .....*..
#23  AF 42 BE 6E 3E 27 2F D2  .B.n>'/.
#24  15 CF 92 80 C2 2A D0 DF  .....*..
#25  0E 3E 5A 9E C1 DC 08 8E  .>Z.....
#26  14 05 E3 C9 ED B0 6B 73  ......ks
#27  94 A3 0E 40 65 DA 2D BF  ...@e.-.
#28  F2 24 B6 39 6B EA A5 07  .$.9k...
#29  C4 94 3D 39 0E 00 B5 F1  ..=9....
#2a  92 1D 1E 87 B8 FA A4 A8  ........
Sensor header CRC16: 5cd1, computed: 0ee2 -> FAILED
Sensor body CRC16: 665d, computed: 76cd -> FAILED
Sensor footer CRC16: 24f2, computed: cf85 -> FAILED
Sensor state: unknown (0x00)
```
Understanding the workflow and ensuring accurate data collection are my primary goals, and any insights into these matters would be incredibly helpful.

**Comment by gui-dos** [comment]
FRAM stands for Ferroelectric RAM: it is a low power non-volatile memory with fast random access, an ideal solution for embedded systems like the TI microcontroller used in the Libre 1 and 2.

In the page https://github.com/captainbeeheart/openfreestyle/blob/master/docs/reverse.md that I am mentioning in my wiki https://github.com/gui-dos/DiaBLE/wiki you can find a dump of the first three regions of the first memory blocks: a “header”, a “body” and a “footer” (3 + 37 + 3 blocks of 8 bytes). The first two bytes of each region contain the CRC checksum code to verify their integrity.

Each measurement consists of 6 bytes and the body stores the latest 16 minutes of data (the “trend” values) and the last 32 “historical” data saved every 15 minutes for the latest 8 hours. These are ring buffers which are overwritten when the pointers to the current values cycle through them.

You found a bug! I am erroneously displaying as “decrypted” for a second time the same encrypted blocks. I am sorry: I never tested Libre 2 US models, just a Libre Sense that I bought by curiosity.

**Comment by gui-dos** [comment]
After selecting “Libre” in the Settings as your preferred transmitter and switching to the third “Test” mode in the Console, you should be able to receive the same data that LibreLink is getting running in parallel.

The Libre 2 sensors advertise every two minutes as a device named "`ABBOTT`" plus their serial number. Any BLE scanner should work, anyway: one of DiaBLE's selling points is that I am offering a full independent BLE scanner for the Apple Watch B-)

**Comment by ElevenRyu** [comment]
> May I ask you whether other parts of my app work with the Libre 2 US, i.e. eavesdropping the incoming BLE data by running in parallel with the official app or scraping online the libreview.io servers?

I don't think it works with Libre2 US. 🥲 
Thanks for your response, I'll close this issue.
