### ISSUE TITLE
Why is libreH not supported?

### ISSUE THREAD

**Issue by zhhehj13** [gui-dos/DiaBLE#15]

**Comment by gui-dos** [comment]
I got some positive feedback from Indian families in the past but I've never tested real Libre H/Pros (most insider info was passed me by @MarekM60).

I am keeping the legacy code in the Playground however (https://github.com/gui-dos/DiaBLE/blob/main/DiaBLE%20Playground.swiftpm/LibrePro.swift) and you can find out some old forks of me still preserving the commit “Drop the Libre Pro” (https://github.com/SimonXuku/DiaBLE-Legacy/commit/1874d6debc43f22e886d74593052eaa6c1d958cb for example) to revert it for the iOS app quite easily ;-)
