### ISSUE TITLE
Unable to see the full  BG reading on Apple Watch

### ISSUE THREAD

**Issue by varunmashru** [gui-dos/DiaBLE#16]
Hi. Because of the bigger font size of the BG reading on the top and the width available, it's not possible to see a 3 digit reading fully. 

Note: I can take up the UX and design part of the app @gui-dos

**Comment by gui-dos** [comment]
Are you using a 40 mm model and getting a truncation like the attached preview?

<img width="237" alt="40mm" src="https://user-images.githubusercontent.com/7220550/160413187-c8af6852-bac4-46ec-b0ec-9f3634efb9eb.png">

I am aware and will try to squeeze correctly.

**Comment by varunmashru** [comment]
Yes. I've already started designing the screens for this. There's a lot of stuff on there any way that needs to be cleaned up.
