### ISSUE TITLE
Some clarification please

### ISSUE THREAD

**Issue by blahdy** [gui-dos/DiaBLE#16]
Forgive me if any of the questions asked are irritating, but I could not find a list of supported models and their limitations.

Could you elaborate what functionality can be expected on a US libre 2? From what I understand it can be read via bluetooth after activating with the native us app? But no history from device, only what's gone through bluetooth? Can it be built with some proprietary library than one has to google himself to have full function?

Also, what will work from the functions menu? Are any of the hacks applicable?

P.S.
Why is there such a bleeding edge ios18 requirement? =0) Managed to build myself the ios17 release, but my interest is for a relative.

**Comment by gui-dos** [comment]
AFAIK, the native methods `P1()` and `P2()` haven’t yet been reversed engineered for the “Gen2” Libre 2 US/CA/AU and even the popular solutions currently available on Android, Juggluco and DiaBox, have to embed and redistribute the native obfuscated binary `libDataProcessing.so`, hence the DMCA takedown request.

Therefore, yes, https://github.com/gui-dos/DiaBLE/blob/946294a404d1197d9507e9a6882752201fcb1ef5/DiaBLE/Gen2.swift#L77-L86 are just dummy placeholders.
