### ISSUE TITLE
OS Requirement

### ISSUE THREAD

**Issue by yanamet** [gui-dos/DiaBLE#18]
Hello, 

What are the OS requirements for connecting a real device with the XCode project? Is the beta 18 iOS version still required as it is in TestFlight? I am having difficulties connecting the device and I have already tried with 2. The developer mode is on. 

Thank you! Looking forward to your answer.

Best regards,
Yana

**Comment by gui-dos** [comment]
Apple has not yet released the Swift Playgrounds 4.6 (5.0?) (https://developer.apple.com/swift-playgrounds/release-notes/) therefore I am keeping them still compilable for iOS/iPadOS 17. You can easily spot the adjustments required to make DiaBLE compilable again for iOS 17 just by searching for "`iOS 18`" comments in the `DiaBLE Playground.swiftpm` project… ;-)

There are just minimal warnings: the only real incompatibility is that I am now using the new iOS 18 `Tabs` in `ContentView`.

**Comment by gui-dos** [comment]
I made the Xcode 16 and iOS 18 requirements highlighted in the README with https://github.com/gui-dos/DiaBLE/commit/07ae0c1.
