### ISSUE TITLE
Changing scan interval from 5 mins(default) to 1 minute changes it permanently for MiaoMiao 3

### ISSUE THREAD

**Issue by varunmashru** [gui-dos/DiaBLE#18]
I was testing out the 1 minute scan interval for my MiaoMiao 3 + Libre Pro combination. I set it back to 5 minutes after a while to start using the Tomato app again. But the scan interval is still set to 1 minute even when using the Tomato app now.

I verified this on the DiaBLE app by checking the rescan timer. After setting it to 5 minutes, it starts at 300 seconds but then goes back to 300 after 60 seconds i.e. after reaching 240 seconds.

**Comment by varunmashru** [comment]
Resetting the MiaoMiao reader set it back to 5 minutes.

**Comment by gui-dos** [comment]
Yep: the MiaoMiao firmware supports the command [`0xD1`](https://github.com/gui-dos/DiaBLE/blob/2752ef95a7fcfdcbf20d736b23379f4b27731ee9/DiaBLE/Devices/MiaoMiao.swift#L53-L55) which lets you set the reading interval to 1, 3 or 5 minutes. If you choose 1 or 3 I am prepending it at a new connection.
