### ISSUE TITLE
Restart Libre 1

### ISSUE THREAD

**Issue by ZeniT21** [gui-dos/DiaBLE#20]
Hello,
Where is restart Libre 1 in this new version?

**Comment by gui-dos** [comment]
In a manual Debug build configuration it is still available under *Tools -> Hacks* (https://github.com/gui-dos/DiaBLE/blob/1c22fac9805836da5d02cf3490b5a095544984a6/DiaBLE/Views/Console.swift#L214-L236) or in the first TestFlight build 144 currently available anyway  ;-)
