### ISSUE TITLE
No such module 'Charts'

### ISSUE THREAD

**Issue by jet-lee-m** [gui-dos/DiaBLE#5]
Hi again,

I am trying to build your restructured version of this git repository. But I cannot build the project because of a missing import (e.g. in OnlineView.swift).

```
import Charts // error --> No such module 'Charts'
```

And I have some other errors in Nightscout.swift, Health.swift, etc. with the following error message.

```
Variable binding in a condition requires an initializer
```

It seems that you are using a different XCode Version or Swift Version than me. I am not sure what I do worng. I am using XCode 13.4.1 and Swift 5 in project. I changed nothing in your code, only the bundle identifier and the signing team.
All this errors occur in the **DiaBLE Watch Extension** code.

Do you know where the problem could be?

**Comment by gui-dos** [comment]
I dropped the support for iOS 15 with https://github.com/gui-dos/DiaBLE/commit/46e18c4 after creating the tag [iOS15](https://github.com/gui-dos/DiaBLE/releases/tag/iOS15) for the nostalgic :-)
