### ISSUE TITLE
Unable to run on a local device

### ISSUE THREAD

**Issue by NovaBG03** [gui-dos/DiaBLE#8]
I'm trying to compile and run the code for iPhone XS MAX but I get these error messages
<img width="677" alt="image" src="https://user-images.githubusercontent.com/43469098/191967818-07f52299-ce86-4aeb-b4a7-30d22ec03f5f.png">

There were no problems running on a simulator but I want to open the app on the local device to test the NFC communication.

**Comment by gui-dos** [comment]
The Core NFC capability requires a paid developer account.

**Comment by NovaBG03** [comment]
Thanks!
