### ISSUE TITLE
libreProH Crash

### ISSUE THREAD

**Issue by zhhehj13** [gui-dos/DiaBLE#9]
The sensor type is libreProH,But when I scan it it crashes
The reason for the crash is because I try to get the FactoryTrend and FactoryHistory
The 'calibrationInfo.i2' is 0 ，cause array out of bounds

**Comment by gui-dos** [comment]
The guard ` calibrationInfo != .empty` at https://github.com/gui-dos/DiaBLE/blob/55493a178d4cb447e506d51640e57d9cd0d30898/DiaBLE/Glucose.swift#L125 is clearly not enough. Could you please post a log until the crash?

**Comment by zhhehj13** [comment]
In this scene the 'calibrationInfo' not empty, so it will go on to run. but  the 'calibrationInfo.i2' is zero,
<img width="805" alt="61D051E4-3B0D-4203-A53A-097AD23136CD" src="https://user-images.githubusercontent.com/45588794/197491094-20750616-54a8-49f8-ad47-010421d20626.png">
as the picture shows，It will cause the array to go out of bounds，then crash

**Comment by zhhehj13** [comment]
HealthKit: authorized
Bluetooth: state: unauthorized
NFC: session did become active
2022-10-24 17:19:48.598080+0800 DiaBLE[894:143419] [CoreNFC] -[NFCTagReaderSession setAlertMessage:]:101 (null)
NFC: did detect tags
NFC: IC identifier: e007a400037c24ca
444行 sensor.securityGeneration = 0
NFC: IC manufacturer code: 0x07 (Texas Instruments)
NFC: firmware version: A4
NFC: memory size: 256 blocks
NFC: block size: 8
NFC: sensor uid: ca247c0300a407e0
NFC: sensor serial number: 1MH006Z14T8
NFC: patch info: 7000100052222902
NFC: sensor type: Libre Pro/H
NFC: sensor security generation [0-3]: 0
457行 368 bytes
NFC: did read 46 FRAM blocks:
#00  C9 71 00 20 03 01 02 07  .q. ....
#01  00 00 00 00 00 00 00 00  ........
#02  00 00 00 00 00 00 00 00  ........
#03  00 00 00 00 00 00 00 00  ........
#04  00 00 00 00 00 00 00 00  ........
#05  99 DD 10 00 14 08 C0 4E  .......N
#06  14 03 96 80 5A 00 ED A6  ....Z...
#07  12 56 DA A0 04 0C D8 66  .V.....f
#08  29 02 C8 18 00 00 00 00  ).......
#09  7A B1 42 11 01 00 26 01  z.B...&.
#0a  30 00 C0 72 A8 04 30 00  0..r..0.
#0b  C0 2A A9 04 2B 00 C0 4A  .*..+..J
#0c  A9 04 2B 00 C0 4E A9 04  ..+..N..
#0d  2D 00 C0 4E A9 04 25 00  -..N..%.
#0e  C0 6A 69 04 28 00 C0 7A  .ji.(..z
#0f  A9 04 27 00 C0 6A A9 04  ..'..j..
#10  28 00 C0 86 A9 04 27 00  (.....'.
#11  C0 9A A9 04 26 00 C0 92  ....&...
#12  A9 04 28 00 C0 96 69 04  ..(...i.
#13  27 00 C0 92 A9 04 27 00  '.....'.
#14  C0 6E A9 04 2E 00 C0 16  .n......
#15  A9 04 31 00 C0 36 A9 04  ..1..6..
#16  71 C1 A0 C0 69 04 56 C1  q...i.V.
#17  A0 38 6A 04 4C C1 A0 3C  .8j.L..<
#18  6A 04 4E C1 A0 10 6A 04  j.N...j.
#19  3F C1 A0 08 6A 04 34 C1  ?...j.4.
#1a  A0 04 6A 04 2E C1 A0 DC  ..j.....
#1b  69 04 2D C1 A0 34 6A 04  i.-..4j.
#1c  27 C1 A0 A8 69 04 2B C1  '...i.+.
#1d  A0 64 69 04 1D C1 A0 1C  .di.....
#1e  6A 04 14 C1 A0 A0 6A 04  j.....j.
#1f  08 C1 A0 34 6B 04 01 C1  ...4k...
#20  A0 A0 6B 04 F7 C0 A0 28  ..k....(
#21  2C 04 F0 C0 A0 68 2C 04  ,....h,.
#22  EC C0 A0 80 2C 04 E6 C0  ....,...
#23  A0 A8 2C 04 E3 C0 A0 C4  ..,.....
#24  2C 04 E0 C0 A0 E8 2C 04  ,.....,.
#25  DB C0 A0 0C 2D 04 D7 C0  ....-...
#26  A0 10 2D 04 D2 C0 A0 1C  ..-.....
#27  6D 04 D0 C0 A0 28 6D 04  m....(m.
#28  CB C0 A0 3C 2D 04 CA C0  ...<-...
#29  A0 4C 6D 04 C5 C0 A0 54  .Lm....T
#2a  2D 04 C1 C0 A0 60 2D 04  -....`-.
#2b  BF C0 A0 64 2D 04 BC C0  ...d-...
#2c  A0 74 2D 04 B8 C0 A0 80  .t-.....
#2d  6D 04 B4 C0 A0 84 6D 04  m.....m.
460行，libreProH scanHistory
DEBUG: fram: 368 bytes, historyData: 192 bytes, historyIndex: 294, startBlock: 196 (#c4), offset: 6, blockCount: 25, history range: 6..<206
NFC: did read 25 FRAM blocks:
#c4  C0 FA 6C 04 00 00 C0 62  ..l....b
#c5  6C 04 00 00 C0 02 AB 04  l.......
#c6  00 00 C0 9A AA 04 00 00  ........
#c7  C0 4E AA 04 00 00 C0 26  .N.....&
#c8  A9 04 00 00 C0 F6 A7 04  ........
#c9  00 00 C8 66 A8 04 00 00  ...f....
#ca  C0 BA 68 04 00 00 C0 1E  ..h.....
#cb  A8 04 00 00 C0 FA A7 04  ........
#cc  00 00 C8 06 A5 04 00 00  ........
#cd  C0 D2 A6 04 00 00 C0 FE  ........
#ce  A7 04 00 00 C0 7E A8 04  .....~..
#cf  00 00 C0 2A A9 04 00 00  ...*....
#d0  C0 66 A9 04 00 00 C0 DE  .f......
#d1  69 04 00 00 C0 1E A9 04  i.......
#d2  00 00 C0 06 A9 04 00 00  ........
#d3  C0 AE A8 04 FD C0 A0 28  .......(
#d4  68 04 00 00 C0 9E 68 04  h.....h.
#d5  00 00 C0 B2 A6 04 00 00  ........
#d6  C0 5A A7 04 00 00 C0 66  .Z.....f
#d7  A7 04 00 00 C0 DE A7 04  ........
#d8  00 00 D0 EA 1D 05 00 00  ........
#d9  C0 62 E4 04 00 00 C0 1E  .b......
#da  A7 04 00 80 C8 CE A4 04  ........
#db  00 00 C0 96 A8 04 00 00  ........
#dc  C0 9A A9 04 98 03 82 68  .......h
462行 1940 bytes
476行，解析数据
468行 sensor类型 Optional(DiaBLE.LibrePro)
Libre Pro/H 1MH006Z14T8: 32 6-byte measurements:
#c4  C0 62 6C 04 00 00 C0 02  .bl.....
#c5  AB 04 00 00 C0 9A AA 04  ........
#c6  00 00 C0 4E AA 04 00 00  ...N....
#c7  C0 26 A9 04 00 00 C0 F6  .&......
#c8  A7 04 00 00 C8 66 A8 04  .....f..
#c9  00 00 C0 BA 68 04 00 00  ....h...
#ca  C0 1E A8 04 00 00 C0 FA  ........
#cb  A7 04 00 00 C8 06 A5 04  ........
#cc  00 00 C0 D2 A6 04 00 00  ........
#cd  C0 FE A7 04 00 00 C0 7E  .......~
#ce  A8 04 00 00 C0 2A A9 04  .....*..
#cf  00 00 C0 66 A9 04 00 00  ...f....
#d0  C0 DE 69 04 00 00 C0 1E  ..i.....
#d1  A9 04 00 00 C0 06 A9 04  ........
#d2  00 00 C0 AE A8 04 FD C0  ........
#d3  A0 28 68 04 00 00 C0 9E  .(h.....
#d4  68 04 00 00 C0 B2 A6 04  h.......
#d5  00 00 C0 5A A7 04 00 00  ...Z....
#d6  C0 66 A7 04 00 00 C0 DE  .f......
#d7  A7 04 00 00 D0 EA 1D 05  ........
#d8  00 00 C0 62 E4 04 00 00  ...b....
#d9  C0 1E A7 04 00 80 C8 CE  ........
#da  A4 04 00 00 C0 96 A8 04  ........
#db  00 00 C0 9A A9 04 98 03  ........
trend= [4, 4, 4, 3, 3, 4, 3, 3, 4, 3, 4, 3, 4, 4, 4, 4]
history= [684, 582, 378, 787, 70, 276, 787, 172, 684, 480, 787, 220, 377, 172, 787, 787, 172, 275, 787, 787, 480, 173, 684, 787, 684, 173, 582, 172, 377, 684, 70, 70]
i2= 0
calibrationInfo= CalibrationInfo(i1: 0, i2: 0, i3: 18, i4: 6742, i5: 8240, i6: 6580)
DEBUG: Libre Pro: trend index: 1, history index: 294, age: 4418 minutes (3d 1h 38m)
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
2022-10-24 17:19:49.180776+0800 DiaBLE[894:143419] Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range

**Comment by gui-dos** [comment]
As a workaround I added a `guard calibrationInfo.i2 != 0` with 9777026.

I can see regular patterns of 6-byte measurements: I should spot now why I am computing bogus trend/historic values…
